"/* =====================================================================
   Plateau de Carrière RH — Données partagées entre index.html et admin.html
   Modifiez ce fichier pour changer le mot de passe ou les contenus par défaut.
   Les modifications faites dans /admin sont stockées dans le localStorage
   du navigateur (clés ci-dessous) et écrasent ces valeurs par défaut.
   ===================================================================== */

const ADMIN_PASSWORD = \"admin2026\";

const STORAGE = {
    squares: \"tc_board_squares_v1\",
    visited: \"tc_board_visited_v1\",
    auth: \"tc_admin_auth_v1\",
    contact: \"tc_contact_info_v1\",
};

const DEFAULT_CONTACT = {
    name: \"Thibaut Casimir\",
    email: \"thibaut.casimir@example.com\",
    phone: \"+33 6 00 00 00 00\",
    linkedin: \"https://www.linkedin.com/in/thibaut-casimir/\",
    cvUrl: \"\",
};

const DEFAULT_SQUARES = [
    // ===== TOP ROW (left -> right) =====
    {
        id: \"contact\",
        x: 13.5, y: 11, width: 11, height: 15.5,
        title: \"Contact\",
        category: \"Échangeons\",
        period: \"Disponible\",
        description: \"Échangeons pour construire la suite de mon parcours RH.\",
        details:
            \"Je reste disponible pour tout échange autour d'opportunités RH, de projets, de partages d'expérience ou simplement d'une discussion autour du métier. N'hésitez pas à me contacter par email ou via LinkedIn.\",
        skills: [\"Email\", \"LinkedIn\", \"Téléphone\"],
        link: \"mailto:contact@example.com\",
        active: true,
    },
    {
        id: \"travail-1\",
        x: 25, y: 12, width: 10.5, height: 14,
        title: \"Travail\",
        category: \"Parcours pro\",
        period: \"2022 — 2024\",
        description: \"Résultats professionnels issus des premières missions opérationnelles.\",
        details: \"Premières expériences professionnelles structurantes : prise en charge de missions RH transverses, accompagnement managérial, support aux opérations et conduite de projets pilotes.\",
        skills: [\"Opérations RH\", \"Reporting\", \"Polyvalence\"],
        link: \"\",
        active: true,
    },
    {
        id: \"hobbies-1\",
        x: 35.7, y: 12, width: 10.5, height: 14,
        title: \"Hobbies\",
        category: \"Hors travail\",
        period: \"Au quotidien\",
        description: \"Défis personnels et leviers professionnels.\",
        details: \"Sport d'endurance, lecture, voyages : autant d'activités qui nourrissent mon équilibre, ma résilience et ma capacité à embarquer les autres dans une dynamique collective.\",
        skills: [\"Endurance\", \"Curiosité\", \"Esprit d'équipe\"],
        link: \"\",
        active: true,
    },
    {
        id: \"gare-3\",
        x: 46.4, y: 12, width: 10.5, height: 14,
        title: \"Gare 3\",
        category: \"Voyages\",
        period: \"Itinérant\",
        description: \"Voyages et ouverture culturelle.\",
        details: \"Une étape parmi d'autres dans un parcours rythmé par les rencontres internationales : Europe, Afrique, Amérique du Nord. Chaque voyage a affiné ma lecture des cultures de travail.\",
        skills: [\"Multiculturalité\", \"Adaptabilité\", \"Curiosité\"],
        link: \"\",
        active: true,
    },
    {
        id: \"travail-2\",
        x: 57.1, y: 12, width: 10.5, height: 14,
        title: \"Travail\",
        category: \"Parcours pro\",
        period: \"2024 — Aujourd'hui\",
        description: \"Résultats professionnels d'expériences plus récentes et stratégiques.\",
        details: \"Pilotage de projets RH plus structurés : déploiement de processus, contribution à la stratégie people, accompagnement du changement et reporting auprès des décideurs.\",
        skills: [\"Pilotage\", \"Stratégie RH\", \"Change\"],
        link: \"\",
        active: true,
    },
    {
        id: \"hobbies-2\",
        x: 67.8, y: 12, width: 10.5, height: 14,
        title: \"Hobbies\",
        category: \"Hors travail\",
        period: \"Au quotidien\",
        description: \"Défis personnels et leviers professionnels.\",
        details: \"Engagement associatif, écriture, photographie : un terrain d'expression qui muscle ma créativité et ma capacité à raconter, deux atouts précieux dans le métier RH.\",
        skills: [\"Créativité\", \"Engagement\", \"Storytelling\"],
        link: \"\",
        active: true,
    },
    {
        id: \"vision-rh\",
        x: 78.5, y: 11, width: 11, height: 15.5,
        title: \"Vision RH\",
        category: \"Boussole\",
        period: \"Pour demain\",
        description: \"Ma boussole RH pour demain.\",
        details: \"Je crois en une fonction RH stratège, humaine et data-éclairée. L'humain au cœur de la performance, la performance au service de l'humain : un équilibre exigeant qui guide chacune de mes décisions.\",
        skills: [\"Stratégie\", \"Éthique\", \"Impact\"],
        link: \"\",
        active: true,
    },

    // ===== RIGHT COLUMN (top -> bottom) =====
    {
        id: \"ouvrages-1\",
        x: 78.8, y: 27.5, width: 11, height: 11.5,
        title: \"Ouvrages\",
        category: \"Lectures\",
        period: \"Bibliothèque\",
        description: \"Lectures qui structurent ma pensée RH.\",
        details: \"Une sélection d'auteurs qui éclairent ma vision : management humaniste, psychologie du travail, leadership, transformation des organisations. Chaque lecture est une occasion de challenger mes pratiques.\",
        skills: [\"Management\", \"Leadership\", \"Sociologie\"],
        link: \"\",
        active: true,
    },
    {
        id: \"engagement-1\",
        x: 78.8, y: 39.2, width: 11, height: 11.5,
        title: \"Engagement\",
        category: \"Impact\",
        period: \"Continu\",
        description: \"Mes moteurs d'impact professionnel.\",
        details: \"Inclusion, mentorat, transmission : je m'engage activement pour que la fonction RH soit un levier concret d'égalité des chances et de développement des talents.\",
        skills: [\"Inclusion\", \"Mentorat\", \"Diversité\"],
        link: \"\",
        active: true,
    },
    {
        id: \"gare-4\",
        x: 78.8, y: 50.8, width: 11, height: 11.5,
        title: \"Gare 4\",
        category: \"Voyages\",
        period: \"Itinérant\",
        description: \"Voyages et ouverture culturelle.\",
        details: \"Une nouvelle escale dans une trajectoire internationale qui forge le regard et l'agilité. Comprendre des contextes différents pour mieux accompagner des équipes diverses.\",
        skills: [\"International\", \"Cultures\", \"Agilité\"],
        link: \"\",
        active: true,
    },
    {
        id: \"ouvrages-2\",
        x: 78.8, y: 62.5, width: 11, height: 11.5,
        title: \"Ouvrages\",
        category: \"Lectures\",
        period: \"Bibliothèque\",
        description: \"Lectures qui structurent ma pratique.\",
        details: \"Plus côté terrain : ouvrages opérationnels sur le recrutement, la GPEC, la rémunération et le dialogue social. Des essentiels pour traduire la vision en actions concrètes.\",
        skills: [\"Recrutement\", \"GPEC\", \"Rémunération\"],
        link: \"\",
        active: true,
    },
    {
        id: \"engagement-2\",
        x: 78.8, y: 74.2, width: 11, height: 11.5,
        title: \"Engagement\",
        category: \"Impact\",
        period: \"Continu\",
        description: \"Mes moteurs d'impact professionnel.\",
        details: \"Qualité de vie au travail, prévention des risques psychosociaux, écoute active : un engagement de fond pour des environnements de travail plus sains et plus performants.\",
        skills: [\"QVCT\", \"Écoute\", \"Prévention\"],
        link: \"\",
        active: true,
    },

    // ===== BOTTOM ROW =====
    {
        id: \"decision-de-vie\",
        x: 13.5, y: 85, width: 11, height: 11,
        title: \"Décision de vie\",
        category: \"Choix structurants\",
        period: \"Étapes clés\",
        description: \"Ces choix personnels qui ont transformé mon parcours.\",
        details: \"Mobilités géographiques, reconversions, prises de risque assumées : chaque décision a été un investissement sur moi-même. Elles ont façonné une trajectoire cohérente et lucide.\",
        skills: [\"Lucidité\", \"Courage\", \"Cohérence\"],
        link: \"\",
        active: true,
    },
    {
        id: \"alternance-1\",
        x: 24.7, y: 86, width: 10.5, height: 10,
        title: \"Alternance\",
        category: \"Expérience clé\",
        period: \"Airbus\",
        description: \"Learning Business Partner — Airbus.\",
        details: \"Au cœur d'un grand groupe industriel, j'ai contribué au déploiement de programmes de formation, à l'analyse des besoins en compétences et à l'accompagnement des managers dans leurs montées en compétences.\",
        skills: [\"Learning\", \"Business Partner\", \"Industrie\"],
        link: \"\",
        active: true,
    },
    {
        id: \"references-1\",
        x: 35.4, y: 86, width: 10.5, height: 10,
        title: \"Références\",
        category: \"Inspirations\",
        period: \"Au fil des rencontres\",
        description: \"Personnalités qui m'inspirent.\",
        details: \"Managers, professeurs, auteurs, mentors : des figures qui ont marqué ma manière de penser le métier. Sur demande, je peux partager des références professionnelles concrètes.\",
        skills: [\"Mentorat\", \"Inspiration\", \"Réseau\"],
        link: \"\",
        active: true,
    },
    {
        id: \"gare-1\",
        x: 46.1, y: 86, width: 10.5, height: 10,
        title: \"Gare 1\",
        category: \"Voyages\",
        period: \"Le départ\",
        description: \"Voyages et ouverture culturelle.\",
        details: \"Première grande étape de mes voyages. L'ouverture par la mobilité, comprendre les autres pour mieux comprendre soi-même — un fondement de ma posture RH.\",
        skills: [\"Mobilité\", \"Ouverture\", \"Curiosité\"],
        link: \"\",
        active: true,
    },
    {
        id: \"alternance-2\",
        x: 56.8, y: 86, width: 10.5, height: 10,
        title: \"Alternance\",
        category: \"Expérience clé\",
        period: \"Airbus\",
        description: \"Learning Business Partner — Airbus.\",
        details: \"Suite de l'expérience Airbus : pilotage de projets transverses, animation de communautés apprenantes et collaboration étroite avec les RRH et managers opérationnels.\",
        skills: [\"Pilotage\", \"Animation\", \"Collaboration\"],
        link: \"\",
        active: true,
    },
    {
        id: \"references-2\",
        x: 67.5, y: 86, width: 10.5, height: 10,
        title: \"Références\",
        category: \"Inspirations\",
        period: \"Au fil des rencontres\",
        description: \"Personnalités qui m'inspirent.\",
        details: \"Une seconde sélection plus contemporaine : leaders inspirants en RH, dirigeants engagés, voix qui réinventent le rapport au travail. Disponibles sur demande.\",
        skills: [\"Leadership\", \"Innovation\", \"Réseau\"],
        link: \"\",
        active: true,
    },
    {
        id: \"depart\",
        x: 78.5, y: 85, width: 11, height: 11,
        title: \"Départ\",
        category: \"Origine\",
        period: \"Le commencement\",
        description: \"Chaque parcours commence par un choix.\",
        details: \"Mon point de départ : la conviction que l'humain est le moteur de toute organisation. C'est cette intuition initiale qui a tracé l'ensemble du chemin présenté ici.\",
        skills: [\"Conviction\", \"Engagement\", \"Démarrage\"],
        link: \"\",
        active: true,
    },

    // ===== LEFT COLUMN =====
    {
        id: \"personnalite-1\",
        x: 13.5, y: 74.2, width: 11, height: 10.5,
        title: \"Personnalité\",
        category: \"Soft skills\",
        period: \"Au quotidien\",
        description: \"Traits au service de la performance.\",
        details: \"Empathie, rigueur, esprit d'analyse, sens du collectif : des qualités cultivées qui me permettent de tenir des sujets RH exigeants tout en gardant l'humain au centre.\",
        skills: [\"Empathie\", \"Rigueur\", \"Analyse\"],
        link: \"\",
        active: true,
    },
    {
        id: \"master-rh-1\",
        x: 13.5, y: 62.5, width: 11, height: 11.5,
        title: \"Master RH\",
        category: \"Formation\",
        period: \"Diplôme\",
        description: \"Projets, apprentissages et compétences RH.\",
        details: \"Master spécialisé en Ressources Humaines : socle solide en droit social, GRH, dialogue social, transformation et data RH. Une formation tournée vers la pratique et la stratégie.\",
        skills: [\"Droit social\", \"GRH\", \"Stratégie\"],
        link: \"\",
        active: true,
    },
    {
        id: \"gare-2\",
        x: 13.5, y: 50.8, width: 11, height: 11.5,
        title: \"Gare 2\",
        category: \"Voyages\",
        period: \"Itinérant\",
        description: \"Voyages et ouverture culturelle.\",
        details: \"Une étape de transition dans mes voyages : prise de recul, observation des modèles managériaux d'ailleurs et confrontation des idées reçues sur le travail.\",
        skills: [\"Recul\", \"Observation\", \"Comparatif\"],
        link: \"\",
        active: true,
    },
    {
        id: \"personnalite-2\",
        x: 13.5, y: 39.2, width: 11, height: 11.5,
        title: \"Personnalité\",
        category: \"Soft skills\",
        period: \"Au quotidien\",
        description: \"Traits au service de la performance.\",
        details: \"Curiosité, fiabilité, énergie communicative, capacité à fédérer : des leviers que je mobilise au service des équipes et des projets, dans les périodes calmes comme tendues.\",
        skills: [\"Fiabilité\", \"Énergie\", \"Fédération\"],
        link: \"\",
        active: true,
    },
    {
        id: \"master-rh-2\",
        x: 13.5, y: 27.5, width: 11, height: 11.5,
        title: \"Master RH\",
        category: \"Formation\",
        period: \"Spécialisations\",
        description: \"Projets, apprentissages et compétences RH.\",
        details: \"Approfondissements thématiques : marque employeur, learning & development, conduite du changement, analyse de données RH. Des terrains d'expérimentation très concrets.\",
        skills: [\"Marque employeur\", \"L&D\", \"Data RH\"],
        link: \"\",
        active: true,
    },
];
"
